In [1]:
import numpy as np # To working with these arrays. 
import pandas as pd # to make working with “relational” or “labeled” data  easy 
import matplotlib.pyplot as plt #To creates a figure, creates a plotting area in a figure, plots some lines in a plotting area,

In [2]:
%matplotlib inline

In [3]:
#Reading  dataset set  
ds = pd.read_csv('cluster_table.csv')                     
ds.head()

          X         Y         Z  Cluster label
0  1.014886  0.750362  1.156124            1.0
1 -0.197795  0.362302  0.884961            1.0
2  0.628812  2.889340  0.019449            1.0
3  0.642886  2.423315  0.329615            1.0
4  2.197576 -0.903305  1.581067            1.0

In [4]:
# Check for null values
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
X                200 non-null float64
Y                200 non-null float64
Z                200 non-null float64
Cluster label    200 non-null float64
dtypes: float64(4)
memory usage: 6.4 KB

In [5]:
ds.describe() #To know mathematical values like min, max,avg of data in each coloumn

                X           Y           Z  Cluster label
count  200.000000  200.000000  200.000000      200.00000
mean     1.308909    1.546920    2.811882        2.50000
std      1.610548    3.298881    4.299736        1.12084
min     -2.917279   -5.722291   -3.576157        1.00000
25%      0.221763   -0.448100    0.209162        1.75000
50%      1.470579    1.476830    1.080962        2.50000
75%      2.569618    4.053052    3.836479        3.25000
max      3.875920    7.102241   12.035278        4.00000

### This data has no missing values and the types are of float64 as displayed above

In [6]:
# creating a data frame with cluster data.
cd = ds[['X', 'Y', 'Z']]

In [7]:
#  new data frame
cd.head()

          X         Y         Z
0  1.014886  0.750362  1.156124
1 -0.197795  0.362302  0.884961
2  0.628812  2.889340  0.019449
3  0.642886  2.423315  0.329615
4  2.197576 -0.903305  1.581067

In [11]:
# extracting each colom separatetly 
x = ds.X.values
y = ds.Y.values
z = ds.Z.values

# tranform to a 1-dim vector
values = np.array([x,y,z]).transpose()

In [12]:
# Standardize features by removing the mean and scaling to unit variance

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(values)
sc_val = scaler.transform(values)  
sc_val

array([[-0.18301895, -0.24206892, -0.38605018],
       [-0.93786982, -0.35999797, -0.44927341],
       [-0.42333619,  0.40795304, -0.65107267],
       [-0.41457552,  0.26633104, -0.57875561],
       [ 0.55316437, -0.74460803, -0.28697212],
       [ 0.4152238 , -0.35689574, -0.43885114],
       [ 0.25461744, -0.30714211, -0.37363864],
       [-0.98932883, -0.45679686, -0.76045091],
       [-0.01641845,  0.10817247, -0.38814717],
       [-0.30806304, -0.2374379 , -0.57901647],
       [-0.11604988, -0.07755127, -0.44016698],
       [-0.06491291, -0.11305114, -0.34562747],
       [-0.20918807,  0.48643333, -0.40164747],
       [ 0.03931171, -0.12874499, -0.6727422 ],
       [ 0.76172545,  0.22372645, -0.46611877],
       [ 0.58540298, -0.27025507, -0.73092928],
       [ 0.06705153, -0.31438692, -0.2345801 ],
       [ 0.66296652, -0.56016293, -0.63224798],
       [-0.17805499, -0.26743242, -0.20393821],
       [-0.27079184, -0.32327606, -0.18149289],
       [-0.67822395,  0.20319642, -0.15282233],
       [-0.03952578, -0.31269788, -0.57722492],
       [-0.27613276, -0.32633284, -0.25539902],
       [ 0.01238693, -0.01827522, -0.43058551],
       [ 0.23378618, -0.21250581, -0.49033621],
       [-0.16167048, -0.08137116, -0.46321566],
       [-0.23390077, -0.24505255, -0.46076896],
       [-0.07057694, -0.21064793, -0.56586205],
       [ 0.58364986, -0.12767161, -0.21934977],
       [-0.16799109, -0.07395824, -0.66706056],
       [ 0.59924185, -0.11279335, -0.5926106 ],
       [ 0.23838534, -0.22985906, -0.35744342],
       [ 0.09294019, -0.42733562, -0.32075968],
       [-0.68814787, -0.23830003, -0.63573188],
       [ 0.01783056, -0.00752082, -0.49101949],
       [-0.50906723, -0.24966362, -0.39745556],
       [-0.43111417, -0.27031046, -0.41497062],
       [ 0.66126776,  0.1361847 , -0.30077589],
       [-0.42859325, -0.130722  , -0.33958845],
       [ 0.05372472, -0.39688097, -0.37406567],
       [-1.10986763,  0.03613573, -0.49022658],
       [-0.71597679, -0.1313862 , -0.59402797],
       [-0.67620516, -0.32314957, -0.60631762],
       [-0.26770529, -0.3398124 , -0.06778281],
       [-0.26901215, -0.2791526 , -0.24898957],
       [-0.65587841,  0.11403075, -0.28395521],
       [-0.50031388, -0.45959934, -0.65324766],
       [-0.7309364 , -0.15484517, -0.73900686],
       [-0.48203979, -0.26311465, -0.4730793 ],
       [ 0.83485404, -0.01149755, -0.26877683],
       [ 0.54339238,  0.12707329,  1.45634063],
       [ 0.96102228,  0.33477201,  1.704394  ],
       [ 0.38544237,  0.38724851,  1.88884409],
       [ 0.61221356, -0.08984183,  1.82721657],
       [ 0.14510929, -0.02432436,  1.843225  ],
       [ 0.0173516 ,  0.13245567,  1.54565942],
       [ 0.31739793,  0.05599938,  1.45629954],
       [ 0.2782345 , -0.16666471,  1.92606673],
       [ 0.06973495, -0.13494273,  1.68264966],
       [-0.3193947 ,  0.66156403,  1.7343464 ],
       [ 0.14609231, -0.13287806,  1.85980833],
       [ 0.54262844, -0.06993757,  1.43477655],
       [ 0.01347776,  0.17450075,  1.72004957],
       [ 0.4777855 ,  0.34897465,  1.60421905],
       [-0.03821181,  0.51713999,  1.78573019],
       [ 0.57164415,  0.07479441,  1.59185256],
       [ 1.45305562,  0.58632316,  1.95731099],
       [ 0.49324262,  0.17085297,  1.47418613],
       [ 0.92520171,  0.39295489,  1.62337447],
       [ 0.40550059, -0.25552664,  1.3639305 ],
       [ 0.47066096,  0.07292543,  1.65459479],
       [ 1.43912981,  0.14779313,  2.15049068],
       [ 0.36789209,  0.08315466,  1.57635735],
       [-0.24883312, -0.24002448,  1.74784069],
       [-0.35009598,  0.27444832,  1.54734274],
       [ 1.21636522, -0.04246968,  1.90826229],
       [ 0.80508619,  0.14318705,  1.7303498 ],
       [ 0.0698874 ,  0.14138138,  1.55942845],
       [-0.0232841 ,  0.01034019,  1.93132951],
       [ 0.06376157,  0.16050339,  1.47630015],
       [ 0.42378921,  0.12656788,  1.26032026],
       [ 0.10832845,  0.26734256,  1.40219033],
       [ 0.02698112,  0.54699759,  1.73075093],
       [ 0.01218774,  0.18640642,  1.76616706],
       [ 0.43751579,  0.11071936,  1.7511107 ],
       [-0.00439633,  0.15058266,  1.33763424],
       [ 0.45498928,  0.0739772 ,  1.60655496],
       [ 0.59267088,  0.2542272 ,  1.32718213],
       [ 0.47399907,  0.14814252,  1.84199543],
       [ 0.51928977,  0.21310656,  1.80488456],
       [ 0.23629305,  0.20352652,  2.03515761],
       [-0.5874148 ,  0.31038534,  1.42817267],
       [ 0.60330532,  0.35686692,  1.69285179],
       [ 0.94552379, -0.26583579,  1.74080637],
       [ 0.32497315,  0.06068513,  1.85368688],
       [ 0.64885593,  0.28112787,  1.15891172],
       [ 0.7304295 ,  0.06058487,  1.73334307],
       [ 0.69044608, -0.06783709,  1.76588103],
       [ 1.29290878, -0.25464356,  1.74669834],
       [ 1.17407771,  0.16914948,  1.88011587],
       [ 0.95009143,  1.38040513, -0.47317256],
       [ 0.65295478,  1.12791653, -0.64109509],
       [ 1.12284322,  1.33060697, -0.1745589 ],
       [ 0.85064917,  1.44247413, -0.36067463],
       [ 0.45686828,  1.38333446, -0.13553126],
       [ 1.29572085,  1.28466906, -0.37982653],
       [ 1.173269  ,  1.35186478, -0.25485868],
       [ 1.11587725,  1.39520905, -0.41171365],
       [ 1.18096433,  1.66192385, -0.28280164],
       [ 1.19927351,  1.46968272, -0.52862644],
       [ 0.81566324,  1.06169961, -0.49359164],
       [ 0.74530452,  1.27094511, -0.4762929 ],
       [ 0.78472513,  1.44171953, -0.39973618],
       [ 1.11947245,  1.39951743, -0.50481815],
       [ 1.54901311,  1.33877983, -0.43353279],
       [ 0.84287919,  1.1696249 , -0.35404781],
       [ 1.25268892,  1.37484161, -0.32434869],
       [ 1.2328609 ,  1.58695523, -0.55666154],
       [ 1.09696466,  1.12142346, -0.46482151],
       [ 0.78481208,  1.21964304, -0.31816117],
       [ 1.12375462,  1.3994527 , -0.3745606 ],
       [ 1.12017147,  1.57396152, -0.40550158],
       [ 0.71550699,  1.45618247, -0.46313273],
       [ 1.15281716,  1.41777965, -0.55330613],
       [ 1.01365811,  1.21577655, -0.20033907],
       [ 1.59373454,  1.42640792, -0.13156741],
       [ 1.51404718,  1.43302371, -0.42097936],
       [ 1.46723123,  1.45084165, -0.42698323],
       [ 0.75527827,  1.34408327, -0.51304023],
       [ 0.82441595,  1.56292089, -0.35633421],
       [ 0.93307243,  1.54908676, -0.35810294],
       [ 0.72846109,  1.68822766, -0.29782816],
       [ 0.91848403,  1.35873667, -0.43258316],
       [ 0.65399183,  1.20484521, -0.35878761],
       [ 0.88321432,  1.2538773 , -0.58241269],
       [ 1.02715968,  1.44218319, -0.51434764],
       [ 1.597874  ,  1.38252897, -0.40727061],
       [ 0.81865936,  1.49892455, -0.65092617],
       [ 0.50698945,  1.36990271, -0.57555733],
       [ 1.17952118,  1.33464098, -0.38731115],
       [ 0.45055301,  1.31070737, -0.31073843],
       [ 1.5573509 ,  1.37689298, -0.32221879],
       [ 0.79426027,  1.41278761, -0.41255345],
       [ 0.99548139,  1.43560091, -0.53141906],
       [ 1.50154232,  1.39014456, -0.38712035],
       [ 1.17967307,  1.21607165, -0.56305342],
       [ 1.01692225,  1.35215534, -0.2752228 ],
       [ 0.70088598,  1.49747595, -0.39076602],
       [ 1.16024373,  1.32903252, -0.29824745],
       [ 0.91167374,  1.33939753, -0.42926959],
       [-2.13170802, -1.74239059, -0.57453966],
       [-1.86261338, -0.53812208, -0.75303282],
       [-1.29218105, -1.88580341, -1.03657099],
       [-1.03753079, -1.11818742, -1.19913342],
       [-1.80320563, -0.74528291, -0.14146851],
       [-0.77179059, -1.60989033, -0.66436047],
       [-2.63065272, -1.42022838, -0.73588279],
       [-1.63360918, -0.95328465, -1.21575323],
       [-1.66847571, -1.07316273, -0.58751897],
       [-0.1333116 , -1.78650479, -0.84512919],
       [-0.80829365, -1.14556888, -0.60840756],
       [-0.9881267 , -1.65666287, -0.59739598],
       [-0.16934235, -1.43950599, -0.6929725 ],
       [-1.85487981, -1.35979468, -1.16719221],
       [-1.2886273 , -0.90517612, -0.84193401],
       [-2.39816385, -0.97533735, -0.56941361],
       [-1.87773183, -1.72797792, -1.1658931 ],
       [-0.69305394, -1.43496238, -0.91067958],
       [-2.2780823 , -1.19584128, -1.03305104],
       [-1.22741603, -1.66209626, -0.25589602],
       [ 0.14016907, -1.24169195, -0.79284359],
       [-0.99417111, -1.17678791, -1.10640061],
       [-1.53027516, -1.30235227, -1.04340593],
       [-1.45914523, -1.54191246, -0.56265482],
       [-1.32709961, -1.43323499, -0.84532394],
       [-1.51665599, -1.61962815, -0.74737041],
       [-0.82787119, -1.02564873, -0.34850947],
       [-1.74060416, -1.05976925, -0.73798663],
       [-2.20495936, -2.20906804, -0.62074633],
       [-1.22841691, -0.99336189, -0.97106517],
       [ 0.00586995, -0.86618634, -0.69161147],
       [-1.79477713, -0.96821887, -1.11351574],
       [-1.78118344, -1.21468624, -0.68513524],
       [-1.53276331, -1.87248512, -1.48941015],
       [-1.30660134, -1.9433034 , -0.91544901],
       [-0.43332509, -1.23791309, -0.70758789],
       [-0.8243112 , -1.14242808, -0.53685055],
       [-0.4787642 , -1.48868055, -0.91629243],
       [-1.37396276, -1.64239614, -1.087149  ],
       [-1.51793851, -1.2728583 , -0.6269269 ],
       [-2.07294975, -0.78228393, -1.01897841],
       [ 1.30578954, -1.90109677, -1.13572568],
       [-1.45607549, -1.40337672, -1.08876602],
       [-2.19280973, -1.49651783, -1.24262833],
       [-1.51451446, -1.70620331, -1.09638843],
       [-2.45331355, -0.92254542, -0.33595601],
       [-0.88102027, -0.88416861, -1.13697827],
       [-1.36746758, -1.77156402, -0.62583695],
       [-1.70388782, -1.68758254, -0.55575919],
       [-0.78698085, -1.01491104, -0.81298509]])

In [13]:
# DBSCAN (Density-Based Spatial Clustering of Applications with Noise) is a popular unsupervised learning method utilized in model building and machine learning algorithms 
from sklearn.cluster import DBSCAN
from sklearn import metrics


dbs = DBSCAN()             

# fit the model on the data also known as trainning the data
db = dbs.fit(scaled_val)

# get all cluster labels  
cl_labels = db.labels_

# Increment the cluster number by 1 
cl_labels=cluster_labels+1
cluster_labels

NameError: name 'scaled_val' is not defined

In [ ]:
# import the plotting library fot 3d plots
from mpl_toolkits.mplot3d import Axes3D

# create a fig and add to the axes
fig = plt.figure(figsize=[15,8])
ax = fig.add_subplot(111, projection='3d')

ax.scatter(sc_val[:,0],sc_val[:,1],sc_val[:,2], c=cl_labels)

In [ ]:
# import all model performance measurement libraries
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score

# set predicted values to cluster labels
pred_val = cluster_labels

true_val = ds['Cluster label'].values.astype(int)

In [ ]:
# display the clustering using the original cluster labels
from mpl_toolkits.mplot3d import Axes3D


fig = plt.figure(figsize=[15,10])
ax = fig.add_subplot(111, projection='3d')
ax.scatter(ds.X, ds.Y, ds.Z, c=ds['Cluster label'])

In [ ]:
print(confusion_matrix(true_val, pred_val))

#### It can be deduced from the confusion matrix that:
- There is noise in the clustering and this is a typical characteristic of the DBSCAN algorithm.
- along the diagonal we have all true positives, i.e the clusters data points that were correctly predicted, 
- this accounts sfor the high f1 score.

In [14]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(true_val, pred_val))

NameError: name 'true_val' is not defined

# http://scikit-learn.org/stable/auto_examples/cluster/plot_dbscan.html
# A-beginners-guide-to- clustering
# youtube'Dataschool'
# scikit learn
# Machine Learning With Python                VASU.T(U34976)